//General
export const SUCCESS_BGCOLOR = '#27ae60';
export const FAILED_BGCOLOR = '#c0392b';

export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

// auth
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const LOGGED_IN_STATUS_CHANGED = 'LOGGED_IN_STATUS_CHANGED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';

export const GET_MYREQUESTS = 'GET_MYREQUESTS';
export const GET_MYREQUESTS_SUCCESS = 'GET_MYREQUESTS_SUCCESS';
export const GET_MYREQUESTS_FAILURE = 'GET_MYREQUESTS_FAILURE';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_REQUESTS_SUCCESS = 'WITHDRAW_REQUESTS_SUCCESS';
export const WITHDRAW_REQUESTS_FAILURE = 'WITHDRAW_REQUESTS_FAILURE';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILURE = 'UPLOAD_FILE_FAILURE ';

export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const QUEUE_REMOVE = 'QUEUE_REMOVE';

// Customer
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER';
export const SEARCH_CUSTOMER_SUCCESS = 'SEARCH_CUSTOMER_SUCCESS';
export const SEARCH_CUSTOMER_FAIL = 'SEARCH_CUSTOMER_FAIL';
export const ADVANCE_SEARCH_CUSTOMER = 'ADVANCE_SEARCH_CUSTOMER';
export const ADVANCE_SEARCH_CUSTOMER_SUCCESS =
    'ADVANCE_SEARCH_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_DETAIL = 'GET_CUSTOMER_DETAIL';
export const GET_CUSTOMER_DETAIL_SUCCESS = 'GET_CUSTOMER_DETAIL_SUCCESS';
export const GET_CUSTOMER_FROM_SAP = 'GET_CUSTOMER_FROM_SAP';
export const RETRIEVE_CUSTOMER_FROM_SAP_SUCCESS =
    'RETRIEVE_CUSTOMER_FROM_SAP_SUCCESS';
export const CUSTOMER_ACTION_MESSAGE = 'CUSTOMER_ACTION_MESSAGE';
// workflow Mytask S1 screen (grid)
export const GET_WORKFLOW = 'GET_WORKFLOW';
export const GET_WORKFLOW_SUCCESS = 'GET_WORKFLOW_SUCCESS';
export const GET_WORKFLOW_FAILURE = 'GET_WORKFLOW_FAILURE';
export const GET_STATUS_BAR_DATA = 'GET_STATUS_BAR_DATA';
export const SET_STATUS_BAR_DATA = 'SET_STATUS_BAR_DATA';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';

export const GET_FUCTIONAL_GROUP_DATA = 'GET_FUCTIONAL_GROUP_DATA';
export const SET_FUCTIONAL_GROUP_DATA = 'SET_FUCTIONAL_GROUP_DATA';

//customer ~ my tasks customer master
export const SAVE_APOLLO_CUSTOMER_MASTER = 'SAVE_APOLLO_CUSTOMER_MASTER';
export const SAVE_APOLLO_CONTRACTS = 'SAVE_APOLLO_CONTRACTS';
export const SAVE_APOLLO_CREDIT = 'SAVE_APOLLO_CREDIT';
export const SAVE_APOLLO_PRICING = 'SAVE_APOLLO_PRICING';
export const SAVE_APOLLO_GLOBALTRADE = 'SAVE_APOLLO_GLOBALTRADE';
export const GET_TAX_JURISDICTION = 'GET_TAX_JURISDICTION';
export const SET_TAX_JURISDICTION = 'SET_TAX_JURISDICTION';
export const RELEASE_CHECKLIST = 'RELEASE_CHECKLIST';

// update process flow
export const GET_MDM_MAPPING_MATRIX = 'GET_MDM_MAPPING_MATRIX';
export const SET_MDM_MAPPING_MATRIX = 'SET_MDM_MAPPING_MATRIX';
export const UPDATE_DELTAS = 'UPDATE_DELTAS';
export const UPDATE_DELTAS_STATUS = 'UPDATE_DELTAS_STATUS';

export const APPROVE_UPDATE_REQUEST = 'APPROVE_UPDATE_REQUEST';
export const APPROVE_UPDATE_SUCCESS = 'APPROVE_UPDATE_SUCCESS';
export const APPROVE_UPDATE_FAILED = 'APPROVE_UPDATE_FAILED';
